"""Process-level swing morphology shared without importing the robot task graph."""

import os


SWING_STRING_LENGTH = float(
    os.environ.get("MICRODUCK_SWING_STRING_LENGTH_M", "0.38")
)
if not 0.20 <= SWING_STRING_LENGTH <= 0.50:
    raise ValueError("MICRODUCK_SWING_STRING_LENGTH_M must be in [0.20, 0.50]")

SWING_STRING_STIFFNESS = 2000.0
SWING_STRING_LIMIT = SWING_STRING_LENGTH + 0.015
SWING_HANG_LENGTH = SWING_STRING_LENGTH + 0.0022
SWING_STRING_MIN_VALID = SWING_STRING_LENGTH - 0.010
SWING_STRING_MAX_VALID = SWING_STRING_LENGTH + 0.014
SWING_STRING_BARRIER_SAFE = SWING_STRING_LENGTH + 0.012
SWING_ANCHOR_HEIGHT = 0.75
SWING_ATTACHMENT_Y = 0.088
SWING_ATTACHMENT_Z = 0.085
SWING_BOTTOM_TRUNK_Z = SWING_ANCHOR_HEIGHT - SWING_HANG_LENGTH - SWING_ATTACHMENT_Z
