"""Stable task API for configurations and previously saved checkpoints.

Implementations live in mdp_terms; keep these aliases when moving terms.
"""

from .runtime_patches import (
    install_runtime_patches,
    _nan_safe_reward_compute,
    _safe_compute_returns,
    _get_base_metadata_no_passive,
)

install_runtime_patches()

from .mdp_terms.common import (  # noqa: E402,F401
    _DEFAULT_ASSET_CFG,
    _NECK_JOINT_PATTERNS,
    _servo_default_joint_pos,
    _servo_joint_ids,
    _servo_joint_pos,
    _servo_joint_vel,
)

from .mdp_terms.locomotion import (  # noqa: E402,F401
    _HIP_PITCH_KNEE_CFG,
    _NECK_JOINT_CFG,
    _ROLLER_FEET_SITE_CFG,
    _crouch_pose_error,
    _forward_progress_gate,
    action_over_limit_penalty,
    adaptive_pose_weight,
    air_time_adaptive,
    body_impact_cost,
    braking_reward,
    coasting_reward,
    com_height_target,
    contact_frequency_penalty,
    crouch_forward_lean,
    crouch_glide_height_by_phase,
    crouch_glide_pose_by_phase,
    crouch_glide_pose_l1,
    crouch_glide_reward_from_values,
    crouch_height_target,
    crouch_pose_blend,
    feet_distance_penalty,
    feet_flat_penalty,
    feet_grounded_reward,
    feet_tiptoe_alignment,
    foot_step_penalty_when_standing,
    forward_lean_reward,
    forward_speed_reward,
    gait_symmetry_penalty,
    glide_reward,
    grounded_reward,
    heading_hold_reward,
    heading_tracking_reward,
    hip_pitch_knee_vel_l2,
    is_alive,
    joint_accelerations_l2,
    joint_torque_rate_l2,
    joint_torques_l2,
    joint_vel_l2_when_standing,
    leg_action_acceleration_l2,
    leg_action_rate_l2,
    leg_joint_vel_l2,
    leg_symmetry_reward,
    neck_action_acceleration_l2,
    neck_action_rate_l2,
    neck_joint_pos_l2,
    neck_joint_vel_l2,
    no_stepping_penalty,
    recovery_stepping_reward,
    reset_action_history,
    reset_rolling_entry,
    reset_with_forward_velocity,
    single_support_reward,
    skating_air_time_reward,
    standing_phase,
    stillness_at_zero_command,
    wheel_glide_reward,
    wheel_speed_reward,
)

from .mdp_terms.recovery import (  # noqa: E402,F401
    _fallen_mask,
    body_ang_vel_at_height,
    body_upright_gaussian,
    body_upright_linear,
    com_upward_velocity,
    descent_speed_reward,
    fallen_state_penalty,
    fallen_too_long,
    feet_air_time_upright,
    height_progress,
    recovery_success,
    root_height_below,
    standing_composite_score,
    standing_success_bonus,
    upright_gaussian_at_height,
    upright_progress,
)

from .mdp_terms.observations import (  # noqa: E402,F401
    _backlash_encoder_ids,
    _finite,
    _imu_misalignment_quat,
    base_ang_vel_imu_misaligned,
    foot_air_time_safe,
    foot_contact_forces_safe,
    foot_height_safe,
    joint_pos_rel_backlash,
    joint_vel_rel_backlash,
    projected_gravity,
    projected_gravity_imu_misaligned,
    raw_accelerometer,
    robot_state_is_nan,
)

from .mdp_terms.running import (  # noqa: E402,F401
    RunningStraightCommand,
    RunningStraightCommandCfg,
    running_command_ranges_curriculum,
    running_flight_event,
    running_forward_progress,
    running_forward_progress_from_velocity,
    running_heading_yaw_rate,
    running_planar_drift_cost,
    running_planar_drift_cost_from_values,
    running_projected_progress,
    running_projected_progress_from_values,
    running_squared_progress,
    running_squared_progress_from_values,
)

from .mdp_terms.ground_pick import (  # noqa: E402,F401
    _gp_phase,
    _kick_pose_error,
    _multistage_target_height,
    _multistage_target_pose,
    _phase_pose_error,
    apply_mouth_payload_force,
    bilateral_symmetry_penalty,
    com_over_support_foot,
    ground_pick_return_pose,
    ground_pick_return_pose_phased,
    ground_pick_return_upright,
    ground_pick_return_upright_phased,
    height_l1_penalty,
    height_target_gaussian,
    interpolated_height_l1_penalty,
    interpolated_height_target,
    interpolated_pose_l1_penalty,
    interpolated_pose_target_match,
    joint_deviation_l1,
    joint_pos_limit_proximity,
    kick_engagement,
    kick_pose_target,
    kick_pose_track,
    kick_pose_track_l1,
    mouth_ground_proximity,
    mouth_ground_proximity_phased,
    mouth_perpendicular_phased,
    mouth_perpendicular_to_ground,
    multistage_height_l1_penalty,
    multistage_height_target,
    multistage_pose_l1_penalty,
    multistage_pose_target_match,
    neck_vel_descent_penalty,
    phase_height_track,
    phase_pose_blend,
    phase_pose_match,
    phase_pose_track,
    phase_pose_track_l1,
    phase_rise_gate,
    pose_l1_penalty,
    pose_target_match,
    sample_mouth_payload,
    seated_stillness,
    sit_grounded,
    sit_stability,
    trunk_downward_velocity_penalty,
    trunk_vertical_accel_penalty,
    upright_while_tall,
)

from .mdp_terms.events import (  # noqa: E402,F401
    _CROUCH_ANCHOR_BY_NAME,
    expand_bam_friction_fields,
    maybe_set_random_prone_orientation,
    randomize_bam_friction,
    randomize_base_orientation,
    randomize_com,
    randomize_delayed_actuator_gains,
    randomize_dof_field_scaled,
    randomize_imu_orientation,
    randomize_mass_and_inertia,
    set_face_down_orientation,
    set_random_crouch_state,
    set_random_ground_state,
    set_random_prone_orientation,
)

from .mdp_terms.curricula import (  # noqa: E402,F401
    com_range_curriculum,
    event_param_curriculum,
    face_down_prob_curriculum,
    pose_command_range_curriculum,
    push_curriculum,
    reward_weight,
    slope_move_masks,
    standing_envs_curriculum,
    termination_param_curriculum,
    terrain_levels_slope,
    velocity_command_ranges_curriculum,
    velocity_tracking_std_curriculum,
    wheel_friction_curriculum,
)

from .mdp_terms.commands import (  # noqa: E402,F401
    GroundPickPhaseCommand,
    GroundPickPhaseCommandCfg,
    RelativeHeadingVelocityCommand,
    RelativeHeadingVelocityCommandCfg,
    SpawnHeadingVelocityCommand,
    SpawnHeadingVelocityCommandCfg,
    UniformPoseCommand,
    UniformPoseCommandCfg,
    VelocityCommandCommandOnly,
    VelocityCommandCommandOnlyCfg,
    zero_command_padding,
)

from .mdp_terms.swing import (  # noqa: E402,F401
    _SWING_GATE_ALIGNMENT_SAFE,
    _SWING_GATE_ALIGNMENT_SCALE,
    _SWING_GATE_DEEP_SLACK_SAFE_M,
    _SWING_GATE_DEEP_SLACK_SCALE_M,
    _SWING_GATE_EXTENSION_SAFE_M,
    _SWING_GATE_EXTENSION_SCALE_M,
    _SWING_GATE_LATERAL_SAFE_M,
    _SWING_GATE_LATERAL_SCALE_M,
    _SWING_SITE_NAMES,
    _swing_kinematics,
    _swing_string_lengths,
    _swing_update_episode_invalid_latch,
    swing_attachment_alignment_barrier_penalty,
    swing_attachment_alignment_penalty,
    swing_bidirectional_peak_progress,
    swing_energy_reward,
    swing_frontier_observation,
    swing_height_reward,
    swing_invalid_episode_debt,
    swing_late_height_reward,
    swing_lateral_barrier_penalty,
    swing_lateral_penalty,
    swing_lateral_velocity_penalty,
    swing_out_of_plane_angular_velocity_penalty,
    swing_physical_validity_factor,
    swing_physical_validity_gate,
    swing_plane_heading_observation,
    swing_predictive_geometry_barrier_from_values,
    swing_predictive_geometry_barrier_penalty,
    swing_state_observation,
    swing_string_extension_barrier_from_lengths,
    swing_string_extension_barrier_penalty,
    swing_string_slack_penalty,
    swing_validity_observation,
)

from .mdp_terms.pose import (  # noqa: E402,F401
    body_pose_tracking_6d,
    body_pose_tracking_locomotion,
    head_pose_bias_penalty,
    head_pose_tracking,
)

from .mdp_terms.ball_kick import (  # noqa: E402,F401
    _ball_kick_dir,
    ball_forward_velocity,
    ball_pos_in_base,
    ball_speed_overshoot_penalty,
    ball_vel_in_base,
    reset_ball_in_front_of_foot,
    single_foot_grounded_reward,
)

from .mdp_terms.spin import (  # noqa: E402,F401
    SPIN_ACCEL_END,
    SPIN_BRAKE_END,
    SPIN_HOLD_END,
    SPIN_LAUNCH_DRIFT_SCALE,
    SPIN_PERIOD,
    SPIN_RATE_MAX,
    SPIN_WHEEL_OMEGA_SCALE,
    _spin_gate,
    _spin_target_rate,
    leg_antisymmetry,
    spin_gate_by_phase,
    spin_grounded,
    spin_phase_from_command,
    spin_rate_by_phase,
    spin_rate_l1,
    spin_rate_reward_from_values,
    spin_rate_track,
    spin_stay_in_place,
    spin_wheel_differential,
    spin_wheel_differential_from_values,
)

from .mdp_terms.sitstand import (  # noqa: E402,F401
    SitStandCommand,
    SitStandCommandCfg,
    _posture_blend,
    _posture_height,
    _posture_targets,
    posture_composite,
    posture_height_gaussian,
    posture_height_l1,
    posture_pose_l1,
    posture_pose_match,
    posture_rise_bootstrap,
    posture_stillness,
    trunk_upward_velocity_penalty,
)

from .mdp_terms.roulade import (  # noqa: E402,F401
    _FLAT_FULL,
    _FLAT_ZERO,
    _HEAD_LATCH_HI,
    _HEAD_LATCH_LO,
    _HEAD_TOP_AXIS,
    _HEAD_TOP_DOWN_MIN,
    _ROULADE_FWD_SIGN,
    _ROULADE_HEAD_SENSOR,
    _ROULADE_SUPPORT_SENSOR,
    _head_top_down,
    _lateral_axis_z,
    _roulade_completion_gate,
    _roulade_state,
    _sensor_any_contact,
    _update_roulade_accum,
    reset_roulade_state,
    roulade_flatness_penalty,
    roulade_head_pivot,
    roulade_height_after_roll,
    roulade_landing_composite,
    roulade_landing_sharp,
    roulade_lateral_velocity_penalty,
    roulade_overspeed_penalty,
    roulade_progress,
    roulade_rise_velocity,
    roulade_sagittal_penalty,
    roulade_stand_tax,
    roulade_upright_after_roll,
)
